# Generated by Django 5.0.7 on 2024-11-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lenguage',
            new_name='language',
        ),
    ]
