# Generated by Django 5.0.7 on 2024-07-30 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_puertas', models.IntegerField(default=0)),
                ('cilindrada', models.IntegerField(default=0)),
                ('combustible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_combustible', to='vehiculos.combustible')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marca_vehiculo', to='vehiculos.marca')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod_vehiculo', to='vehiculos.modelo')),
                ('pais_fabricacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='vehiculos.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='vehiculos.vehiculo')),
            ],
        ),
    ]
