# Generated by Django 5.0.7 on 2024-07-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='cilindrada',
            field=models.FloatField(default=0),
        ),
    ]
