# Generated by Django 5.0.7 on 2024-07-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_vehiculo_cilindrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='precio_en_dolares',
            field=models.FloatField(default=0),
        ),
    ]
