# Generated by Django 5.0.7 on 2024-08-08 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculo_precio_en_dolares'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='vehiculo_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.vehiculo')),
            ],
        ),
    ]
