# Generated by Django 5.0.7 on 2024-10-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_remove_vehiculoimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoimage',
            name='ruta_imagen',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculoimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
