# Generated by Django 5.0.7 on 2024-11-06 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_vehiculoimage_ruta_imagen_alter_vehiculoimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='calificacion',
            field=models.IntegerField(default=0, verbose_name='calificacion'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='vehiculos.vehiculo', verbose_name='vehiculo'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cant_puertas',
            field=models.IntegerField(default=0, verbose_name='cant_puertas'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cilindrada',
            field=models.FloatField(default=0, verbose_name='cilindrada'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_combustible', to='vehiculos.combustible', verbose_name='combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marca_vehiculo', to='vehiculos.marca', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod_vehiculo', to='vehiculos.modelo', verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='pais_fabricacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='vehiculos.pais', verbose_name='pais_fabricacion'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='precio_en_dolares',
            field=models.FloatField(default=0, verbose_name='precio_en_dolares'),
        ),
        migrations.AlterField(
            model_name='vehiculoimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='vehiculoimage',
            name='ruta_imagen',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='ruta_imagen'),
        ),
        migrations.AlterField(
            model_name='vehiculoimage',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.vehiculo', verbose_name='vehiculo'),
        ),
    ]
